### ISSUE TITLE
child containers should do "late binding"

### ISSUE THREAD

**Issue by nicops** [dsawardekar/encase#4]
I'll explain this with an example:

```
class A
   def a
      b 
   end
   def b
      puts "hello" 
   end
end

class B < A
   def b
      puts "hello world" 
   end
end

```

`B.new.a` outputs "hello world", because the method "b" is late binded.

Similary, if I do something like

```
container = Container.new
container.configure do
   object :logger, Logger.new
   factory :house, House
end

child = container.child
child.configure do
   object :logger, MagicLogger.new
end
```

If I do `child.lookup(:house)`, and the House needs logger, it should use MagicLogger, not Logger.

**Comment by dsawardekar** [comment]
Hey @nicops, sorry for the late reply.

This is fixed in 0.1.2. Thanks for reporting.
